name: "Setup Node + pnpm + install"
description: "Shared setup for pnpm workspaces"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
