/**
 * Storybook Fluent localization wiring
 * ---
 * Storybook consumes a virtual Fluent bundle generated by the Vite l10n plugin.
 *
 * High-level flow:
 * 1. The Vite plugin scans co-located `component.ftl` files in the repo.
 * 2. Those files are concatenated into a single virtual module:
 *    `virtual:fluent/<surface>/<locale>`.
 * 3. Storybook loads that virtual module on startup and initializes Fluent DOM
 *    once for the preview roots.
 * 4. During dev, when any tracked `.ftl` file changes, the plugin rebuilds the
 *    in-memory bundle and emits a custom HMR event instead of forcing a full
 *    page reload.
 * 5. Storybook receives that event, swaps the current raw FTL source, clears
 *    parsed bundle cache, recreates DOMLocalization, and re-translates roots.
 *
 * Why both `clearCache()` and `setLocales()`?
 * - `clearCache()` drops cached `FluentBundle` instances created from older FTL.
 * - `setLocales()` recreates `DOMLocalization`, reconnects roots, and runs a
 *   fresh translation pass immediately.
 *
 * This is intentionally Storybook-dev-only behavior:
 * - no generated files
 * - no full-page flash on FTL edits
 * - no Storybook-specific behavior inside the shared l10n runtime
 *
 * Source of truth:
 * - Vite plugin owns bundle aggregation and file watching
 * - `@common/l10n` owns Fluent runtime behavior
 * - Storybook preview owns dev-time HMR glue
 */

import fg from "fast-glob"
import fs from "node:fs/promises"
import path from "node:path"

type Options = {
  surface: string
  locale: string
  sources: string | string[]
  repoRoot?: string
}

function normalizeNewlines(s: string) {
  return s.replace(/\r\n/g, "\n")
}

function escapeTemplateLiteral(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`")
}

function makeVirtualId(surface: string, locale: string) {
  return `virtual:fluent/${surface}/${locale}`
}

export function fluentL10n(opts: Options) {
  const repoRoot = opts.repoRoot ?? process.cwd()
  const sources = Array.isArray(opts.sources) ? opts.sources : [opts.sources]

  const virtualId = makeVirtualId(opts.surface, opts.locale)
  const resolvedVirtualId = `\0${virtualId}`

  let cachedFtl = ""
  let builtOnce = false
  let version = 0

  async function getMatchedFiles() {
    const files = await fg(sources, {
      cwd: repoRoot,
      onlyFiles: true,
      unique: true,
      ignore: [
        "**/node_modules/**",
        "**/.git/**",
        "**/.turbo/**",
        "**/dist/**",
        "**/build/**",
      ],
    })

    files.sort((a, b) => a.localeCompare(b))
    return files
  }

  async function buildBundle() {
    const files = await getMatchedFiles()

    let out = `# -----------------------------------------------------------------------------
# VIRTUAL (IN-MEMORY) BUNDLE — DO NOT EDIT
# Surface: ${opts.surface}
# Locale: ${opts.locale}
# Matched files: ${files.length}
# -----------------------------------------------------------------------------

`

    for (const rel of files) {
      const abs = path.join(repoRoot, rel)
      const raw = await fs.readFile(abs, "utf8")
      out += `# --- ${rel} ---\n`
      out += normalizeNewlines(raw).trimEnd() + "\n\n"
    }

    const changed = out !== cachedFtl
    cachedFtl = out
    builtOnce = true

    if (changed) {
      version += 1
    }

    return { changed, files }
  }

  function moduleCode() {
    return `export const surface = ${JSON.stringify(opts.surface)};
export const locale = ${JSON.stringify(opts.locale)};
export const version = ${JSON.stringify(version)};
export const ftl = \`${escapeTemplateLiteral(cachedFtl)}\`;
export default ftl;
`
  }

  return {
    name: "fluent-l10n-virtual-bundle",
    enforce: "pre",

    resolveId(id: string) {
      if (id === virtualId) return resolvedVirtualId
      return null
    },

    async load(id: string) {
      if (id !== resolvedVirtualId) return null

      if (!builtOnce) {
        await buildBundle()
      }

      return moduleCode()
    },

    async buildStart() {
      await buildBundle()
    },

    async configureServer(server: any) {
      const { files } = await buildBundle()

      const absFiles = files.map((rel) => path.join(repoRoot, rel))
      const absDirs = [...new Set(absFiles.map((file) => path.dirname(file)))]

      server.watcher.add(absFiles)
      server.watcher.add(absDirs)
      server.watcher.add(sources)
    },

    async handleHotUpdate(ctx: any) {
      if (!ctx.file.endsWith(".ftl")) return

      const relChanged = path.relative(repoRoot, ctx.file).replace(/\\/g, "/")
      const matched = await getMatchedFiles()

      if (!matched.includes(relChanged)) return

      const { changed } = await buildBundle()
      if (!changed) return []

      const mod = ctx.server.moduleGraph.getModuleById(resolvedVirtualId)
      if (mod) {
        const invalidated = new Set()
        ctx.server.moduleGraph.invalidateModule(
          mod,
          invalidated,
          ctx.timestamp,
          true,
        )
      }

      ctx.server.ws.send({
        type: "custom",
        event: "fluent:bundle-updated",
        data: {
          version,
          ftl: cachedFtl,
        },
      })

      return []
    },
  }
}
